CREATE TABLE CLIENTE (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    CPF VARCHAR(11)
);

CREATE TABLE PRODUTO (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(100),
    PRECO_UNITARIO NUMERIC(20,2)
);

CREATE TABLE PEDIDO (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CLIENTE_ID INTEGER REFERENCES CLIENTE (ID),
    DATA_PEDIDO TIMESTAMP,
    STATUS VARCHAR(20)
    TOTAL NUMERIC(20,2)
);

CREATE TABLE ITEM_PEDIDO (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    PEDIDO_ID INTEGER REFERENCES PEDIDO (ID),
    PRODUTO_ID INTEGER REFERENCES PRODUTO (ID),
    QUANTIDADE INTEGER
);

CREATE TABLE ENDERECO (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    LOGRADOURO VARCHAR(100),
    BAIRRO VARCHAR(50),
    CIDADE VARCHAR(50),
    UF VARCHAR(2),
    NUMERO(VARCHAR(10)),
    COMPLEMENTO VARCHAR(100),
    CEP VARCHAR(10)
);

CREATE TABLE TRANSPORTADORA (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    VALOR NUMERIC(20,2)
);

